#!/usr/bin/env python3
"""Write tokens.css from tokens.json, or check that it is what tokens.json writes.

    python3 tools/build.py            write tokens.css
    python3 tools/build.py --check    refuse where tokens.css or tokens.json is wrong

tokens.json is the source and tokens.css is generated from it and committed, so that a
client pins either file at a tag and reads it as it is, with no build of its own. The two
must never disagree, which is what --check holds, and tokens.json must keep to what the
documentation's Design system chapter fixes, which is what these rules hold:

- Both grounds carry the same tokens, among them every one the chapter lists: a client
  switching ground finds each token it used on the other.
- Every colour is written #RRGGBB in capitals, so that one value is spelled one way and a
  search finds every use of it.
- running is the accent on each ground: the chapter makes it "the one state that borrows
  the accent hue", and two values that must be equal are one value typed twice.
- Each type role names a face the tokens declare, at a weight that face is loaded with: a
  weight nobody loads is drawn by the browser's synthesis, never by the typeface.
- Every gap is a whole number of base units, since the unit is what the rhythm is made of.

Standard library only: the design repository has nothing else to install, and a token
file that needs a toolchain to read is one a client stops reading.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tokens.json"
TARGET = ROOT / "tokens.css"

# The tokens the Design system chapter lists, by the names it gives them. Anything else in
# tokens.json is derived from the chapter's mockups and named there too.
CORE = [
    "sunken", "bg", "surface", "raised", "faint", "muted", "text",
    "accentDim", "accent", "succeeded", "running", "waiting", "failed",
]

HEX = re.compile(r"^#[0-9A-F]{6}$")


def refuse(problems):
    for p in problems:
        print(f"tokens.json: {p}", file=sys.stderr)
    raise SystemExit(1)


def check_source(t):
    problems = []
    grounds = t["colour"]
    if set(grounds) != {"dark", "light"}:
        problems.append(f"colour has grounds {sorted(grounds)}, where dark and light are the two there are")
    names = {g: list(v) for g, v in grounds.items()}
    if len(set(map(tuple, map(sorted, names.values())))) != 1:
        only = {g: sorted(set(v) - set().union(*(set(o) for h, o in names.items() if h != g))) for g, v in names.items()}
        problems.append(f"the grounds carry different tokens: {only}")
    for g, values in grounds.items():
        for name in CORE:
            if name not in values:
                problems.append(f"{g} lacks {name}, which the Design system chapter lists")
        for name, value in values.items():
            if not HEX.match(value):
                problems.append(f"{g}.{name} is {value!r}, not #RRGGBB in capitals")
        if values.get("running") != values.get("accent"):
            problems.append(f"{g}.running is {values.get('running')}, where it is the accent, {values.get('accent')}")

    fonts = t["font"]
    for role, spec in t["type"].items():
        face = fonts.get(spec["font"])
        if face is None or not isinstance(face, dict):
            problems.append(f"type.{role} names the face {spec['font']!r}, which font does not declare")
            continue
        for key in ("weight", "weightActive", "weightName"):
            if key in spec and spec[key] not in face["weights"]:
                problems.append(f"type.{role}.{key} is {spec[key]}, a weight {spec['font']} is not loaded with")

    unit = t["density"]["unit"]
    for gap in t["density"]["gaps"]:
        if gap % unit:
            problems.append(f"the gap {gap} is not a whole number of {unit}px units")

    if problems:
        refuse(problems)


def px(value):
    return f"{value:g}px"


def stack(face):
    names = [face["family"], *face["fallback"]]
    generic = {"sans-serif", "serif", "monospace", "ui-monospace", "system-ui"}
    return ", ".join(n if n in generic or " " not in n else f'"{n}"' for n in names)


def colours(values, indent):
    return "".join(f"{indent}--{name}: {value};\n" for name, value in values.items())


def render(t):
    out = []
    out.append("/* Generated by tools/build.py from tokens.json: edit that file and run the build, never this one.\n")
    out.append("   Light is the default ground; dark follows the reader's system unless data-theme=\"light\" is set\n")
    out.append("   on the root, and data-theme=\"dark\" forces it, as the site and the console both do. */\n\n")

    out.append(":root {\n")
    out.append("  color-scheme: light;\n")
    out.append(colours(t["colour"]["light"], "  "))
    out.append("\n")
    out.append(f"  --font-sans: {stack(t['font']['sans'])};\n")
    out.append(f"  --font-mono: {stack(t['font']['mono'])};\n")
    out.append("\n")
    for role, spec in t["type"].items():
        out.append(f"  --type-{role}-font: var(--font-{spec['font']});\n")
        size = spec["size"]
        if isinstance(size, dict):
            out.append(f"  --type-{role}-size-min: {px(size['min'])};\n")
            out.append(f"  --type-{role}-size-max: {px(size['max'])};\n")
        else:
            out.append(f"  --type-{role}-size: {px(size)};\n")
        for key in ("weight", "weightActive", "weightName"):
            if key in spec:
                out.append(f"  --type-{role}-{key}: {spec[key]};\n")
        if "tracking" in spec:
            out.append(f"  --type-{role}-tracking: {spec['tracking']};\n")
        if "case" in spec:
            out.append(f"  --type-{role}-case: {spec['case']};\n")
        if "lineHeight" in spec:
            lh = spec["lineHeight"]
            out.append(f"  --type-{role}-lineHeight-min: {px(lh['min'])};\n")
            out.append(f"  --type-{role}-lineHeight-max: {px(lh['max'])};\n")
    out.append("\n")
    d = t["density"]
    units = ", ".join(str(g // d["unit"]) for g in d["gaps"])
    out.append(f"  /* Gaps are {units} units: calc(var(--unit) * n). */\n")
    out.append(f"  --unit: {px(d['unit'])};\n")
    out.append(f"  --window-min: {px(d['window']['min'])};\n")
    for group in ("bar", "row", "padding", "radius", "border"):
        for name, value in d[group].items():
            out.append(f"  --{group}-{name}: {px(value)};\n")
    out.append("}\n\n")

    dark = colours(t["colour"]["dark"], "    ")
    out.append("@media (prefers-color-scheme: dark) {\n")
    out.append("  :root:not([data-theme=\"light\"]) {\n")
    out.append("    color-scheme: dark;\n")
    out.append(dark)
    out.append("  }\n")
    out.append("}\n\n")
    out.append(":root[data-theme=\"dark\"] {\n")
    out.append("  color-scheme: dark;\n")
    out.append(colours(t["colour"]["dark"], "  "))
    out.append("}\n")
    return "".join(out)


def main():
    checking = "--check" in sys.argv[1:]
    tokens = json.loads(SOURCE.read_text(encoding="utf-8"))
    check_source(tokens)
    css = render(tokens)
    if checking:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != css:
            print("tokens.css is not what tokens.json writes: run python3 tools/build.py and commit both", file=sys.stderr)
            raise SystemExit(1)
        print("tokens.json keeps to the rules, and tokens.css is what it writes")
        return
    TARGET.write_text(css, encoding="utf-8")
    print(f"wrote {TARGET.name}")


if __name__ == "__main__":
    main()
