#!/usr/bin/env python3
"""Write mark/wordmark.svg: the lowercase wordmark as outlines, from Archivo Bold.

    python3 tools/wordmark.py path/to/Archivo-Bold.ttf

The lockup is the mark beside the wordmark, and a lockup file that asks for Archivo draws
in whatever face the viewer happens to have when it is missing. So the wordmark is kept as
outlines, taken once from the face and committed, and tools/build.py sets them beside the
mark it draws. This is run by hand when the wordmark or the face changes, which is why it
alone needs fontTools and uharfbuzz: the build and its check stay on the standard library.

The shape follows the lockup rule of the Design system chapter and tokens.json's
mark.lockup: the text at `size` units, where the mark is 16 wide, tracked by `tracking`
ems between letters, its baseline `baseline` units below the mark's top, and shaped by
HarfBuzz with the face's own kerning, as a browser sets it. The outline starts at 0 on the
x axis; the build moves it `gap` units past the mark.

Archivo is under the SIL Open Font License 1.1, which lets its outlines be used in a mark.
"""

import json
import sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    font_path = sys.argv[1]
    lockup = json.loads((ROOT / "tokens.json").read_text(encoding="utf-8"))["mark"]["lockup"]
    tracking = float(lockup["tracking"].removesuffix("em"))

    tt = TTFont(font_path)
    name = tt["name"].getDebugName(4)
    version = tt["name"].getDebugName(5)
    if name != "Archivo Bold":
        raise SystemExit(f"{font_path} is {name!r}, where the wordmark is Archivo Bold")
    upm = tt["head"].unitsPerEm
    scale = lockup["size"] / upm

    face = hb.Face(hb.Blob.from_file_path(font_path))
    font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(lockup["wordmark"])
    buf.guess_segment_properties()
    hb.shape(font, buf, {"kern": True, "liga": False})

    order = tt.getGlyphOrder()
    glyphs = tt.getGlyphSet()
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{round(v, 3):g}")
    bounds = BoundsPen(glyphs)
    x = 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        # Font units grow upwards and SVG units downwards, so y is flipped about the baseline.
        transform = (scale, 0, 0, -scale, (x + pos.x_offset) * scale, lockup["baseline"])
        glyphs[order[info.codepoint]].draw(TransformPen(pen, transform))
        glyphs[order[info.codepoint]].draw(TransformPen(bounds, transform))
        x += pos.x_advance + tracking * upm
    # The outline's own box, which the build reads to size the lockup rather than parsing
    # curves: the ink, not the advance, since a lockup is measured by what it shows.
    x0, y0, x1, y1 = (round(v, 3) for v in bounds.bounds)

    out = ROOT / "mark" / "wordmark.svg"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "<!-- Generated by tools/wordmark.py from "
        f"{name} {version}: the wordmark as outlines, which tools/build.py sets beside the mark. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0:g} {y0:g} {round(x1 - x0, 3):g} {round(y1 - y0, 3):g}">'
        f'<path d="{pen.getCommands()}"/></svg>\n',
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)} from {name} {version}")


if __name__ == "__main__":
    main()
